Feature to enable or disable SSL for Postgres
bitnami/bitnami-docker-keycloak pull request #18
Opened 2021-08-16 11:45 UTC by vrtata

**Description of the change**

The change implements an environment variable which enables switching on SSL mode for database connections during deployment.

**Benefits**

With the increase in usage of cloud databases, it is required by organization to connect to databases over SSL. In some cases it is mandatory.

**Possible drawbacks**

None

**Applicable issues**

Please refer to the issue # 6217 titled "[bitnami/keycloak] unable to specify sslmode for external PostgreSQL database #6217"

**Additional information**

2021-08-17 13:12 UTC, rafariossaa commented
Hi,
  Thanks for this providing this functionality.
  I am doing the internal changes to acomodate this before merging it.

2021-08-17 13:14 UTC, rafariossaa commented
Could you add the new environment variables  to the README ?

2021-08-18 08:57 UTC, rafariossaa requested changes
Sorry, I realized about a couple of details.

Could you take care of them? 
One is renaming the new environment variable, and the other is adding a validation for the new environment variable values, for example:

```diff
diff --git a/images/generic/lib/libkeycloak.sh b/images/generic/lib/libkeycloak.sh
index a9c1a001085f9..2217266b7c3da 100644
--- a/images/generic/lib/libkeycloak.sh
+++ b/images/generic/lib/libkeycloak.sh
@@ -65,7 +65,7 @@ keycloak_validate() {
     check_allowed_port KEYCLOAK_HTTP_PORT
     check_allowed_port KEYCLOAK_HTTPS_PORT
 
-    for var in KEYCLOAK_CREATE_ADMIN_USER KEYCLOAK_ENABLE_TLS KEYCLOAK_ENABLE_STATISTICS; do
+    for var in KEYCLOAK_CREATE_ADMIN_USER KEYCLOAK_ENABLE_TLS KEYCLOAK_ENABLE_STATISTICS KEYCLOAK_DATABASE_TLS; do
         if ! is_true_false_value "${!var}"; then
             print_validation_error "The allowed values for $var are [true, false]"
         fi
```

2021-08-18 08:57 UTC, rafariossaa commented on 13/debian-10/rootfs/opt/bitnami/scripts/keycloak-env.sh
> +KEYCLOAK_DATABASE_SSL="${KEYCLOAK_DATABASE_SSL:-"${DB_SSL:-}"}"
Please, could you rename this environment variable as `KEYCLOAK_DATABASE_TLS` ?. This is for coherence with the rest of containers.

2021-08-18 12:28 UTC, vrtata commented
Sure. I will make the necessary changes and submit a new pull request

2021-08-19 09:12 UTC, rafariossaa approved these changes
LGTM.

2021-08-19 09:12 UTC, merged