Add support for specifying JDBC parameters to the connection string
bitnami/bitnami-docker-keycloak pull request #22
Opened 2021-09-16 19:51 UTC by vl4d1m1r4

**Description of the change**

This PR replaces the `KEYCLOAK_DATABASE_TLS` environment variable with a more robust `KEYCLOAK_JDBC_PARAMS` variable which enables to specify multiple parameters to the JDBC driver for Postgres. Also the `useSSL` doesn't really do anything as explained in issue #21.

**Benefits**

With this change the user can specify multiple parameters, some of them include controlling the `connectionTimeout` and in our use case to specify different `sslmode=verify-full` and override the paths for the `sslrootcert`, `sslcert` and `sslkey` to allow passwordless connection to a database using certificates.

**Possible drawbacks**

Anyone using the `KEYCLOAK_DATABASE_TLS` variable should update it to `KEYCLOAK_JDBC_PARAMS=useSSL\=true|false`, but as mentioned in #21 this doesn't seem to do anything to the connection string (I think this is MySQL specific parameter).

**Applicable issues**

#21 

**Additional information**

The `KEYCLOAK_JDBC_PARAMS` variable should not include the `?` in the beginning, it will be automatically added.

2021-09-17 16:57 UTC, marcosbc requested changes
Thanks for the PR! I've added some requests, let me know if you have any questions.

2021-09-17 16:57 UTC, marcosbc commented on 14/debian-10/rootfs/opt/bitnami/scripts/keycloak-env.sh
> +KEYCLOAK_JDBC_PARAMS=$(echo "${KEYCLOAK_JDBC_PARAMS:-"${JDBC_PARAMS:-}"}" | sed '/^$/! s/^/?/')
Currently we try to avoid adding any hidden logic in the `*-env.sh` files, apart from setting constants and defaults for environment variables. I think it would be better to, instead of automatically doing it, throw an error in `keycloak_validate` if it does not have the expected format, or even automatically formatting it in `keycloak_initialize`. What do you think?

2021-09-17 16:57 UTC, marcosbc commented on 14/debian-10/rootfs/opt/bitnami/scripts/keycloak-env.sh
> -export KEYCLOAK_DATABASE_TLS="${KEYCLOAK_DATABASE_TLS:-false}"
Instead of removing this environment variable, we could add some logic in `keycloak_initialize` to automatically append `tls=true` to the current value of `KEYCLOAK_JDBC_PARAMS`, if `KEYCLOAK_DATABASE_TLS` is set. That would avoid breaking any current use cases and it seems like a simple improvement to implement.

Any concerns against that?

2021-09-19 16:04 UTC, vl4d1m1r4 commented on 14/debian-10/rootfs/opt/bitnami/scripts/keycloak-env.sh
> +KEYCLOAK_JDBC_PARAMS=$(echo "${KEYCLOAK_JDBC_PARAMS:-"${JDBC_PARAMS:-}"}" | sed '/^$/! s/^/?/')
Great, will make the change, I will also append '?' only if it is missing instead of validating it.

2021-09-19 16:08 UTC, vl4d1m1r4 commented on 14/debian-10/rootfs/opt/bitnami/scripts/keycloak-env.sh
> -export KEYCLOAK_DATABASE_TLS="${KEYCLOAK_DATABASE_TLS:-false}"
Adding `useSSL` parameter doesn't do anything for Postgres driver, it is just ignored so I think it should be removed as nothing will break, it is an obsolete parameter.  But, if you insist I can also add the logic to include it if the environment variable is set.

2021-09-22 15:47 UTC, marcosbc commented on 14/debian-10/rootfs/opt/bitnami/scripts/keycloak-env.sh
> -export KEYCLOAK_DATABASE_TLS="${KEYCLOAK_DATABASE_TLS:-false}"
I see, the new option would be `sslmode`. If so, this LGTM!

2021-09-22 15:47 UTC, marcosbc approved these changes
LGTM, thanks a lot for this great improvement!

2021-09-23 06:58 UTC, vl4d1m1r4 commented on 14/debian-10/rootfs/opt/bitnami/scripts/keycloak-env.sh
> -export KEYCLOAK_DATABASE_TLS="${KEYCLOAK_DATABASE_TLS:-false}"
`sslmode` in adition with `ssl` parameter because it is the one that enables ssl. `sslmode` is not mandatory and has default value `prefer`. For example for our use case we want to switch it to `verify-full` and the complete `KEYCLOAK_JDBC_PARAM` would look like this: `KEYCLOAK_JDBC_PARAM=ssl=true&sslrootcert=/path/to/ca.crt&sslcert=/path/to/client.crt&sslkey=/path/to/client.key`.

2021-09-23 08:33 UTC, merged