added --auto-build param to start command
bitnami/bitnami-docker-keycloak pull request #91
Opened 2022-07-07 07:58 UTC by rpiecyk

After changes from https://github.com/bitnami/bitnami-docker-keycloak/commit/920085ca2eea6aa90c9e21c1f86d1c89aae01952 there is no `kc.sh build` command run during entrypoint execution. As a result, any necessary changes made to config `/opt/bitnami/keycloak/conf/keycloak.conf` meant for a build step are conflicting with defaults, resulting in errors.
 
**Description of the change**
Addition of `--auto-build` flag to the `start_param` variable in `/opt/bitnami/scripts/keycloak/run.sh` script.

**Benefits**
Everytime a change to parameters is detected by a server a build will be triggered before running keycloak start command.
https://www.keycloak.org/server/configuration#_the_auto_build_option_automatic_detection_when_the_server_needs_a_build

**Possible drawbacks**
Slightly longer execution time.

**Applicable issues**
https://github.com/bitnami/charts/issues/11067

**Additional information**
As of now a helm chart running the image cannot be used in production mode for 18.0.2-debian-11-r1 and newer release.

2022-07-08 08:32 UTC, rafariossaa commented on 18/debian-11/rootfs/opt/bitnami/scripts/keycloak/run.sh
> +is_boolean_yes "$KEYCLOAK_PRODUCTION" && start_param="start --auto-build" || start_param="start-dev"
Have you checked this ?
I think it could lead to some issue because start --auto-build" is going to be treated as only an argument whereas it is two.

```
$ start_param="start --auto-build"
$ start_command=("${KEYCLOAK_BIN_DIR}/kc.sh" "-cf" "$conf_file" "$start_param")

$ echo "${start_command[*]}"
/kc.sh -cf  start --auto-build

$ echo "${start_command[1]}"
-cf
$ echo "${start_command[2]}"

$ echo "${start_command[3]}"
start --auto-build
```

2022-07-15 20:08 UTC, rpiecyk commented on 18/debian-11/rootfs/opt/bitnami/scripts/keycloak/run.sh
> +is_boolean_yes "$KEYCLOAK_PRODUCTION" && start_param="start --auto-build" || start_param="start-dev"
I don't think it would interfere with a correct script execution but I updated the code - tried to make it in more bitnami-way, so hopefully it will be fine now

2022-07-18 09:42 UTC, rafariossaa requested changes

2022-07-18 09:42 UTC, rafariossaa commented on 18/debian-11/rootfs/opt/bitnami/scripts/keycloak-env.sh
> +export AUTO_BUILD="${AUTO_BUILD:-false}"
Sorry, I should brought this out on the first review.
Could you rename this environment variable to something like: `KEYCLOAK_ENABLE_AUTOBUILD` 
This way it is more similar to what we usually do in containers.

2022-07-28 14:55 UTC, carrodher commented
In order to unify the approaches followed for Bitnami containers and Bitnami Helm charts, we are moving the different `bitnami/bitnami-docker-<container>` repositories to a single repository: `bitnami/containers`.

Please could you create this PR in the [`bitnami/containers` monorepository](https://github.com/bitnami/containers)? Thank

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html

2022-07-28 14:56 UTC, closed without merging